#!/bin/sh

echo "Cloning repo"
git clone --recursive https://github.com/arnm/.emacs.d ~/.emacs.d

echo "Downloading default custom.el"
cd ~/.emacs.d/
wget https://gist.githubusercontent.com/arnm/11359580/raw/00d81bde6480835a0cdab9301783b81f7123581e/custom.el

echo "Setup complete"
